# Generated by Django 3.2.6 on 2021-12-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
